### ISSUE TITLE
Not loading status when click 

### ISSUE THREAD

**Issue by vulieumang** [HubSpot/messenger#116]
Hi :)
I download example, upload to localhost, and click run below example, but the loading status not show correct. I only see it run correctly  on home page this project.
![not-circle2](https://cloud.githubusercontent.com/assets/13487753/16574522/fc55e530-42a9-11e6-9444-3b1db92355d0.gif)

```javascript
var i;

i = 0;

Messenger().run({
  errorMessage: 'Error destroying alien planet',
  successMessage: 'Alien planet destroyed!',
  action: function(opts) {
    if (++i < 3) {
      return opts.error({
        status: 500,
        readyState: 0,
        responseText: 0
      });
    } else {
      return opts.success();
    }
  }
});

```

**Comment by vulieumang** [comment]
I was found how to fix it.
correct this line like me
```css
.messenger-spinner .messenger-spinner-side-left .messenger-spinner-fill {
  left: 100%;
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
  -webkit-animation-name: ui-spinner-rotate-left;
  -moz-animation-name: ui-spinner-rotate-left;
  -ms-animation-name: ui-spinner-rotate-left;
  -o-animation-name: ui-spinner-rotate-left;
  animation-name: ui-spinner-rotate-left;
  -webkit-transform-origin: 0 50%;
  -moz-transform-origin: 0 50%;
  -ms-transform-origin: 0 50%;
  -o-transform-origin: 0 50%;
  transform-origin: 0 50%;
}
```
![fix](https://cloud.githubusercontent.com/assets/13487753/16610319/cba9ba3e-4384-11e6-8246-00460621c5e8.JPG)

Any body help me to contribute to this project?
