### ISSUE TITLE
Is there messenger-on-center in extraClasses?

### ISSUE THREAD

**Issue by clinyong** [HubSpot/messenger#78]
I want to set the message box in the center of the screen, but the official doc seems not to support this option in extraClasses.

**Comment by geekjuice** [comment]
While it's not officially supported yet, you could add a custom class in your stylesheets e.g. `messenger-center` that centers the dialog. A simple (albeit naive and potentially flawed) solution could be:

```css
.messenger-center {
    top: 50%;
    left: 50%;
    width: 350px;
    margin-left: -175px;
}
```

While this will work, remember that `Messenger` can stack and will generally start to look janky at that point. __However__, if you are looking for a alert-style dialog box, __HubSpot__ actually has another project that does just that called [Vex](http://github.hubspot.com/vex/docs/welcome/) that you should definitely check out. :smile:
