### ISSUE TITLE
Possible to copy/paste text from a pop-up?

### ISSUE THREAD

**Issue by ralphbean** [HubSpot/messenger#95]
It would be nice to be able to select and copy text from a pop-up, but I don't seem to be able to on Chrome or Firefox.

Would it be possible to add this?

**Comment by baoshan** [comment]
Text selection is disabled by theme css (I have no idea why, actually). You can override it by:

```css
ul.messenger-theme-your-theme {
  user-select: text;
}
```
